### ISSUE TITLE
Page turning and jumping issues

### ISSUE THREAD

**Issue by sFireFrog** [CloudNativeGame/kruise-game-dashboard#2]
1.Clicking on the specified type of game service set will not jump to the specified type of game service.
2.The number of game servers is greater than the set number of displays per page and there is no page turning.

**Comment by jayesh9747** [comment]
@ringtail  Was this issue completed or not? I want to work on it.

**Comment by ringtail** [comment]
> @ringtail Was this issue completed or not? I want to work on it.

Sure,you can take it.

**Comment by jayesh9747** [comment]
@ringtail  can you help me out ? i am facing this issue 

![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/123955234/fa0779ee-f544-4b71-8bf3-848f9c11b648)

according to this pic ks-api-server ip address replace with which ip address ? 

i replace ip  add. with this ip  

![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/123955234/2cfd7814-11ab-4690-9417-ef991e743018)

but it give me the TLE. 

![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/123955234/6f690627-c8e2-486b-9160-7a331881463e)


i also try this ip 

![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/123955234/6e42de8a-b237-48a8-9bef-d96d2e3a1c5b)

Patiently awaiting your response

**Comment by 2008sahil** [comment]
Hey @ringtail ,i am also intersted in this project and tried to setup the project locally but when i run yarn dev and access the localhost:8000 i am getting the kubeshpere dashboard but not extension 
![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/155609546/7c10cac5-c2e8-4ab9-b223-7b282dad3f2a)
also i am getting page not found error on backend 
![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/155609546/979e469b-9ba1-4eb6-95d7-b7025d1821f7)
 can you please help

**Comment by ringtail** [comment]
> @ringtail can you help me out ? i am facing this issue
> 
> ![image](https://private-user-images.githubusercontent.com/123955234/331554530-fa0779ee-f544-4b71-8bf3-848f9c11b648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xMjM5NTUyMzQvMzMxNTU0NTMwLWZhMDc3OWVlLWY1NDQtNGI3MS04YmYzLTg0OGY5YzExYjY0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDFhMWYyMmJhNDU3NGUyODcxODcwZGRmYjFiMWM4ZTk3ZmM3ZGVmOGZjYTNhZWRmZTYyYTI1OTU4MDk3YjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8-h3mueL5aShSiIhdQxUixhsZCH-v3tsZbyjTrva2aA)
> 
> according to this pic ks-api-server ip address replace with which ip address ?
> 
> i replace ip add. with this ip
> 
> ![image](https://private-user-images.githubusercontent.com/123955234/331554811-2cfd7814-11ab-4690-9417-ef991e743018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xMjM5NTUyMzQvMzMxNTU0ODExLTJjZmQ3ODE0LTExYWItNDY5MC05NDE3LWVmOTkxZTc0MzAxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk5NWIwYzA2ODk0NDdlYzIwY2YzOGZhMWYzMzM5MWJiMTk4ZDI1NmE4MzRmYmIxMDVmMGMzOTlhZWJmMWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HcuCyIY-OjBeFOCnfhdiwhmMFJif2QAZDJd_FypJTHw)
> 
> but it give me the TLE.
> 
> ![image](https://private-user-images.githubusercontent.com/123955234/331563880-6f690627-c8e2-486b-9160-7a331881463e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xMjM5NTUyMzQvMzMxNTYzODgwLTZmNjkwNjI3LWM4ZTItNDg2Yi05MTYwLTdhMzMxODgxNDYzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTI2Yzc2NTdmZjY1MmY2ZWU5NWJiYTY3ZTgyNTJlNjhjYjI2YmEwYTNjMTc3ZDkyZjdmYmNmODRiMWNlMWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v8cbmjafdWEdJt-jhHG0_mJEmkGSWsnpZINV9twK2_Q)
> 
> i also try this ip
> 
> ![image](https://private-user-images.githubusercontent.com/123955234/331563691-6e42de8a-b237-48a8-9bef-d96d2e3a1c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xMjM5NTUyMzQvMzMxNTYzNjkxLTZlNDJkZThhLWIyMzctNDhhOC05YmVmLWQ5NmQyZTNhMWM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGViNzEyMjJlYmRjNDQ5YWM0N2UyZjk1ZDE4MTc2MDg2N2E1ZWEwYTcxYWE2ZTAyYjc2YjE4YjBkYjMzZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxmlF6X4EoJrOtLitgHu-0hbfhICnlg-U4LsCXGh0js)
> 
> Patiently awaiting your response

replace it with KubeShpere Web Console IP:Port

**Comment by ringtail** [comment]
> Hey @ringtail ,i am also intersted in this project and tried to setup the project locally but when i run yarn dev and access the localhost:8000 i am getting the kubeshpere dashboard but not extension ![image](https://private-user-images.githubusercontent.com/155609546/331894128-7c10cac5-c2e8-4ab9-b223-7b282dad3f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xNTU2MDk1NDYvMzMxODk0MTI4LTdjMTBjYWM1LWMyZTgtNGFiOS1iMjIzLTdiMjgyZGFkM2YyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDczYzlmNjM3ZmZkYjA2ODUxOTVlOGY2M2JjZGYzMWVhNjExODI3ZDE3OGMxNjU4NTFjN2ZjOGQ1OWJhMWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C_SimCckYq8XnQ1dl-VkaToXzYOnZNq3DCOafqTJWmU) also i am getting page not found error on backend ![image](https://private-user-images.githubusercontent.com/155609546/331894174-979e469b-9ba1-4eb6-95d7-b7025d1821f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIzODgsIm5iZiI6MTcxNjE3MjA4OCwicGF0aCI6Ii8xNTU2MDk1NDYvMzMxODk0MTc0LTk3OWU0NjliLTliYTEtNGViNi05NWQ3LWI3MDI1ZDE4MjFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGI4Y2UxYWQ1ODE2NmVjOWVhNmQ2ZTNjODg2NTRlYzRkYTZhZmFjZTUzZmQwZDY0OTlmMjRkYzI5NzhjNDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fua4qh6YSwXJnJpgPFmqSe2gsuIro3UfUAPLDTLlIF0) can you please help

it should be inside of one cluster detail.

**Comment by 2008sahil** [comment]
hi @ringtail , I hope you are doing well. I am very interested in working on this project and would love to contribute to resolving the page turning and jumping issues. I have successfully set up the project locally and am able to access the Kruise game dashboard on my local machine.

![image](https://github.com/CloudNativeGame/kruise-game-dashboard/assets/155609546/3851e878-87ac-47b7-a3d2-4ebf3d4a7e16)
Could you please assign this issue to me? I am eager to dive in and help address the problem.

**Comment by 2008sahil** [comment]
@ringtail , I’m working on resolving the following issues with the GameServerList component :

Filtering Game Server Sets by Type:

Current Approach: I’m exploring the use of query parameters in the API request to filter by server type but haven’t found a suitable parameter yet. Another option could be adding a condition to each column for client-side filtering.
Request: Does the API support filtering by server type through query parameters? If not, could you suggest the best way to implement client-side filtering?

Enabling Pagination:

Current Approach: I understand that DataTable handles pagination internally, likely via the formatServerData function. I need more clarity on this process.
Request: Could you provide documentation or guidance on how the DataTable component manages pagination and the role of formatServerData?
Any insights or advice you can provide would be greatly appreciated.
